/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#1b1c1c",
        "tertiary-fixed-dim": "#c7c7ba",
        "on-tertiary-container": "#a8a99b",
        "surface-variant": "#e4e2e1",
        "secondary-fixed": "#ffe088",
        "on-primary-fixed": "#410000",
        "on-background": "#1b1c1c",
        "surface-container-high": "#eae8e7",
        "secondary-container": "#fed65b",
        "inverse-on-surface": "#f3f0f0",
        "on-primary-fixed-variant": "#8f0f07",
        "surface-container-low": "#f6f3f2",
        "on-primary-container": "#ff8371",
        "inverse-surface": "#303030",
        "surface-tint": "#b22b1d",
        "primary-fixed": "#ffdad4",
        "surface-bright": "#fbf9f8",
        "surface-container-highest": "#e4e2e1",
        "outline": "#8e706c",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#ffb4a8",
        "on-tertiary-fixed-variant": "#46483d",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "background": "#fbf9f8",
        "surface-container": "#f0eded",
        "tertiary-fixed": "#e3e3d5",
        "surface-dim": "#dcd9d9",
        "primary-container": "#800000",
        "primary": "#570000",
        "on-tertiary-fixed": "#1b1c14",
        "outline-variant": "#e2bfb9",
        "secondary": "#735c00",
        "error": "#ba1a1a",
        "inverse-primary": "#ffb4a8",
        "on-surface-variant": "#5a413d",
        "on-secondary-fixed-variant": "#574500",
        "on-primary": "#ffffff",
        "tertiary": "#26281f",
        "tertiary-container": "#3c3e34",
        "on-secondary-container": "#745c00",
        "surface": "#fbf9f8",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary-fixed": "#241a00",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "background-light": "#fbf9f8",
        "background-dark": "#1b1c1c",
        "text-light": "#1b1c1c",
        "text-dark": "#fbf9f8",
        "accent": "#735c00"
      },
      fontFamily: {
        "heading": ["'Montserrat'", "sans-serif"],
        "body": ["'Montserrat'", "sans-serif"],
        "logo": ["'Playfair Display'", "serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
